version: '3.9'

services:
  web:
    build: .
    command: gunicorn asset_data.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped